[project]
name = "structure-aware-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fatahillahgg", email = "farisazizfatahillah@student.telkomuniversity.ac.id" }
]
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.9",
    "pydantic>=2.13.5",
    "unstructured[pdf]>=0.27.5",
]

[project.scripts]
structure-aware-rag = "structure_aware_rag:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
